// AUTO-GENERATED BY DSM MANAGER — DO NOT EDIT MANUALLY
// Use DSM > Open Manager to modify entries.

using UnityEngine;

public static partial class DSMConstant
{
    public const int testKey = 24;
    public const string anotherKey = "Hello, DSM!";
    public static readonly Vector2 TestPos = new Vector2(1f, 1f);
}
