#nullable enable
#if UNITY_EDITOR

using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

public static class DSMCodeGenerator
{
    private const string OutputPath = "Assets/DataSaveManager/Runtime/DSMConstant.cs";

    public static void Generate(IReadOnlyList<DSMDataEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED BY DSM MANAGER — DO NOT EDIT MANUALLY");
        sb.AppendLine("// Use DSM > Open Manager to modify entries.");
        sb.AppendLine();
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine("public static partial class DSMConstant");
        sb.AppendLine("{");

        foreach (var entry in entries)
        {
            if (string.IsNullOrWhiteSpace(entry.Key)) continue;
            if (char.IsLower(entry.Key[0]))
                Debug.LogWarning($"DSM: Key '{entry.Key}' does not follow PascalCase convention. Consider renaming it.");
            sb.AppendLine($"    {BuildDeclaration(entry)}");
        }

        sb.AppendLine("}");

        var newContent = sb.ToString();

        // Skip write + recompile if content is identical (e.g. window re-opened with no changes)
        if (File.Exists(OutputPath) && File.ReadAllText(OutputPath, Encoding.UTF8) == newContent)
            return;

        Directory.CreateDirectory(Path.GetDirectoryName(OutputPath)!);
        File.WriteAllText(OutputPath, newContent, Encoding.UTF8);
        AssetDatabase.Refresh();
        Debug.Log($"DSM: Generated {OutputPath} with {entries.Count} entries.");
    }

    private static string BuildDeclaration(DSMDataEntry e)
    {
        var d = e.SerializedDefault;
        return e.Type switch
        {
            DSMDataType.Int    => $"public const int {e.Key} = {ParseInt(d)};",
            DSMDataType.Float  => $"public const float {e.Key} = {ParseFloat(d).ToString("G", CultureInfo.InvariantCulture)}f;",
            DSMDataType.Double => $"public const double {e.Key} = {ParseDouble(d).ToString("G", CultureInfo.InvariantCulture)};",
            DSMDataType.Long   => $"public const long {e.Key} = {ParseLong(d)}L;",
            DSMDataType.Bool   => $"public const bool {e.Key} = {ParseBool(d).ToString().ToLower()};",
            DSMDataType.String => $"public const string {e.Key} = \"{EscapeString(d)}\";",
            DSMDataType.Vector2 => $"public static readonly Vector2 {e.Key} = {Vec2Literal(d)};",
            DSMDataType.Vector3 => $"public static readonly Vector3 {e.Key} = {Vec3Literal(d)};",
            DSMDataType.Vector4 => $"public static readonly Vector4 {e.Key} = {Vec4Literal(d)};",
            DSMDataType.Color   => $"public static readonly Color {e.Key} = {ColorLiteral(d)};",
            _ => $"// Unsupported type: {e.Type}"
        };
    }

    private static int ParseInt(string s) =>
        int.TryParse(s, NumberStyles.Any, CultureInfo.InvariantCulture, out var v) ? v : 0;

    private static float ParseFloat(string s) =>
        float.TryParse(s, NumberStyles.Any, CultureInfo.InvariantCulture, out var v) ? v : 0f;

    private static double ParseDouble(string s) =>
        double.TryParse(s, NumberStyles.Any, CultureInfo.InvariantCulture, out var v) ? v : 0.0;

    private static long ParseLong(string s) =>
        long.TryParse(s, NumberStyles.Any, CultureInfo.InvariantCulture, out var v) ? v : 0L;

    private static bool ParseBool(string s) =>
        bool.TryParse(s, out var v) && v;

    private static string EscapeString(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");

    private static float[] SplitFloats(string s, int count)
    {
        var parts = s.Split(',');
        var result = new float[count];
        for (int i = 0; i < count; i++)
            result[i] = i < parts.Length ? ParseFloat(parts[i].Trim()) : 0f;
        return result;
    }

    private static string F(float v) => v.ToString("G", CultureInfo.InvariantCulture) + "f";

    private static string Vec2Literal(string s)
    {
        var f = SplitFloats(s, 2);
        return $"new Vector2({F(f[0])}, {F(f[1])})";
    }

    private static string Vec3Literal(string s)
    {
        var f = SplitFloats(s, 3);
        return $"new Vector3({F(f[0])}, {F(f[1])}, {F(f[2])})";
    }

    private static string Vec4Literal(string s)
    {
        var f = SplitFloats(s, 4);
        return $"new Vector4({F(f[0])}, {F(f[1])}, {F(f[2])}, {F(f[3])})";
    }

    private static string ColorLiteral(string s)
    {
        var f = SplitFloats(s, 4);
        if (f[3] == 0f && !s.Contains(',', System.StringComparison.Ordinal)) f[3] = 1f;
        return $"new Color({F(f[0])}, {F(f[1])}, {F(f[2])}, {F(f[3])})";
    }
}

#endif
